# Generated by Django 4.1.12 on 2024-01-31 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("installation_date", models.DateField()),
                (
                    "monthly_charges",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("billing_date", models.DateField()),
                ("renewal_date", models.DateField()),
                ("role", models.CharField(max_length=255)),
                (
                    "business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.business",
                    ),
                ),
            ],
            options={
                "db_table": "sales",
            },
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "sale_items",
            },
        ),
        migrations.AlterUniqueTogether(
            name="contractitem",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="contractitem",
            name="contract",
        ),
        migrations.RemoveField(
            model_name="contractitem",
            name="item",
        ),
        migrations.RemoveField(
            model_name="contractitem",
            name="person",
        ),
        migrations.RemoveField(
            model_name="item",
            name="contract_items",
        ),
        migrations.RemoveField(
            model_name="person",
            name="contract_items",
        ),
        migrations.DeleteModel(
            name="Contract",
        ),
        migrations.DeleteModel(
            name="ContractItem",
        ),
        migrations.AddField(
            model_name="saleitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.item"
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.person",
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.sale"
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.person"
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="sale_items",
            field=models.ManyToManyField(through="home.SaleItem", to="home.item"),
        ),
        migrations.AddField(
            model_name="item",
            name="sale_items",
            field=models.ManyToManyField(through="home.SaleItem", to="home.sale"),
        ),
        migrations.AddField(
            model_name="person",
            name="sale_items",
            field=models.ManyToManyField(through="home.SaleItem", to="home.person"),
        ),
        migrations.AlterUniqueTogether(
            name="saleitem",
            unique_together={("sale", "item")},
        ),
    ]
