# Generated by Django 4.1.12 on 2024-01-31 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_sale_saleitem_alter_contractitem_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sale",
            old_name="monthly_charges",
            new_name="charges",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="billing_date",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="installation_date",
        ),
        migrations.AddField(
            model_name="sale",
            name="payment_interval",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Monthly", "Monthly"),
                    ("Quarterly", "Quarterly"),
                    ("Half-Yearly", "Half-Yearly"),
                    ("Yearly", "Yearly"),
                    ("Manual", "Manual"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[("One-time", "One-time"), ("Recurring", "Recurring")],
                default="One-time",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="purchase_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="sale",
            name="renewal_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
