# Generated by Django 4.1.12 on 2024-01-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_contract_contractequipment_person_equipment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")], max_length=1
            ),
        ),
    ]
