# Generated by Django 4.1.12 on 2024-01-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_rename_monthly_charges_sale_charges_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="billing_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
