# Generated by Django 4.1.12 on 2024-01-24 04:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_business_user_owner_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="business",
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.DeleteModel(
            name="Owner",
        ),
        migrations.DeleteModel(
            name="Staff",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
