# Generated by Django 4.1.12 on 2024-01-24 05:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_user_owner_staff"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Owner",
        ),
        migrations.DeleteModel(
            name="Staff",
        ),
    ]
