# Generated by Django 4.1.12 on 2024-02-04 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_delete_product_person_unique_email_per_business"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="person",
            unique_together={("email", "business")},
        ),
    ]
