# Generated by Django 4.1.12 on 2024-02-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_alter_person_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(max_length=255),
        ),
    ]
