# Generated by Django 4.1.12 on 2024-02-04 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_person_email"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="person",
            unique_together=set(),
        ),
    ]
