# Generated by Django 4.1.12 on 2024-01-24 05:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_user_groups_alter_user_user_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="business",
        ),
    ]
