# Generated by Django 4.1.12 on 2024-01-24 05:38

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("home", "0009_remove_user_business"),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("home.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name="user",
            old_name="type",
            new_name="role",
        ),
        migrations.AddField(
            model_name="user",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.business",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="auth.permission",
            ),
        ),
    ]
