# Generated by Django 4.1.12 on 2024-02-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_alter_sale_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[("One-Time", "One-Time"), ("Recurring", "Recurring")],
                default="One-Time",
                max_length=20,
            ),
        ),
    ]
