# Generated by Django 4.1.12 on 2024-01-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="business_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
