# Generated by Django 4.1.12 on 2024-01-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_alter_business_name"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="user",
        #     name="business_name",
        # ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
