# Generated by Django 4.1.12 on 2024-01-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_remove_user_business_name_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="business_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
