# Generated by Django 4.1.12 on 2024-01-25 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_user_business_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="business_name",
            field=models.CharField(
                blank=True, default=django.utils.timezone.now, max_length=255
            ),
            preserve_default=False,
        ),
    ]
