# Generated by Django 4.1.12 on 2024-01-25 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0018_user_business_name"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="user",
        #     name="business_name",
        # ),
    ]
