# Generated by Django 4.1.12 on 2024-01-26 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0020_remove_user_business_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.business",
            ),
        ),
    ]
